language: node_js
git:
    depth: 5
node_js:
    - "6"
    - "8"
    - "10"
install:
    - npm install
before_script:
    - git clone --depth 1 https://github.com/twbs/bootstrap.git --branch v3-dev || travis_terminate 1
    - bundle install --deployment --gemfile bootstrap/Gemfile --jobs=3 --retry=3 || travis_terminate 1
    - pushd bootstrap && bundle exec jekyll build && popd
script:
    - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run nyc -- npm run test && npm run qunit; else npm run test; fi || travis_terminate 1
    - node ./src/cli-main.js --disable W003,W005 "bootstrap/_gh_pages/**/index.html" || travis_terminate 1
    - node ./src/cli-main.js test/fixtures/x-ua-compatible/missing.html &> x-ua-compatible-missing.output.actual.txt || true
    - diff test/fixtures/cli/x-ua-compatible-missing.output.txt x-ua-compatible-missing.output.actual.txt
after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run coveralls; fi
matrix:
    fast_finish: true
cache:
    directories:
        - node_modules
notifications:
    email: false
