{
    "sudo": false,
    "dist": "trusty",
    "language": "node_js",
    "node_js": ["4", "8"],
    "before_install": [
        "if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi"
    ],
    "install": [
        "npm install -g grunt-cli",
        "npm install",
        "bundle install --deployment --jobs=3 --retry=3"
    ],
    "before_script": [
        "git clone --depth 1 https://github.com/twbs/bootstrap.git --branch v3-dev",
        "pushd bootstrap && jekyll build; popd"
    ],
    "matrix": [
        "fast_finish": true
    ],
    "script": [
        "npm test",
        "./src/cli-main.js bootstrap/_gh_pages/**/index.html",
        "./src/cli-main.js --disable W003,E001 test/fixtures/doctype/missing.html test/fixtures/viewport/missing.html",
        "./src/cli-main.js test/fixtures/x-ua-compatible/missing.html &> x-ua-compatible-missing.output.actual.txt || true",
        "diff test/fixtures/cli/x-ua-compatible-missing.output.txt x-ua-compatible-missing.output.actual.txt"
    ],
    "after_script": [
        "npm run coveralls"
    ],
    "cache": {
        "directories": [
            "node_modules",
            "vendor/bundle"
        ]
    }
}
